
version: "3.9"

services:
  web:
    image: my-app2:latest           
    ports:
      - "8080:80"                      
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
  
